name: Docker registry

on: 
   push:
     tags:
       - 'v*'

jobs:
  dockerhub-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :python
        if: success()
        run: docker build -t aoirint/ffmpeg:python --build-arg BASE_IMAGE=python:3 .

      - name: Push to docker hub :python
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/ffmpeg:python

  dockerhub-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: docker.io

      - name: Build :ubuntu
        if: success()
        run: docker build -t aoirint/ffmpeg:ubuntu --build-arg BASE_IMAGE=ubuntu:bionic .

      - name: Push to docker hub :ubuntu
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/ffmpeg:ubuntu

      - name: Build :tag
        if: success()
        run: docker build -t aoirint/ffmpeg:${IMAGE_TAG} .

      - name: Push to docker hub :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/ffmpeg:${IMAGE_TAG}

      - name: Push to docker hub :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push aoirint/ffmpeg:latest
