name: Docker registry

on:
  push:
    branches:
      - main
  release:
    types:
      - created

env:
  IMAGE_NAME: aoirint/ffmpeg
  IMAGE_TAG: ${{ github.event.release.tag_name != '' && github.event.release.tag_name || 'latest' }}

jobs:
  push:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag_prefix: ''
            base_image: 'ubuntu:focal'
          - tag_prefix: 'ubuntu-'
            base_image: 'ubuntu:focal'
          - tag_prefix: 'nvidia-'
            base_image: 'nvcr.io/nvidia/driver:515-signed-ubuntu20.04'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          IMAGE_NAME_AND_TAG: ${{ format('{0}:{1}{2}', env.IMAGE_NAME, matrix.tag_prefix, env.IMAGE_TAG) }}
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
          tags: ${{ env.IMAGE_NAME_AND_TAG }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME_AND_TAG }}-buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME_AND_TAG }}-buildcache,mode=max
